### ISSUE TITLE
Are there any unit tests available

### ISSUE THREAD

**Issue by major** [googleapis/python-grpc-google-iam-v1#4]
I package this project in [Fedora Linux](https://src.fedoraproject.org/rpms/python-grpc-google-iam-v1) and I prefer to run unit tests during the RPM build to ensure everything has built properly and will work with the modules installed in Fedora. However, I cannot find any unit tests in this repository.

Are the tests held somewhere else or does this module not have any tests? Thanks!

**Comment by vam-google** [comment]
This module contains only automatically generated stubs (the`_pb2.py` files) by [protoc](https://github.com/protocolbuffers/protobuf) from corresponding `.proto` files. The correctness of the automatically generated code is supposed to be tested by the corresponding tests in the generator (protoc), not by generating/writing test for the generated code. So yes, this module does not have tests by design.
